INSERT INTO Book (title, author_name) VALUES
('Harry Potter','J.K. Rowling'),
('The Hobbit','J.R.R. Tolkien'),
('1984','George Orwell'),
('Animal Farm','George Orwell'),
('Pride and Prejudice','Jane Austen'),
('The Great Gatsby','F. Scott Fitzgerald'),
('To Kill a Mockingbird','Harper Lee'),
('The Catcher in the Rye','J.D. Salinger'),
('The Alchemist','Paulo Coelho'),
('The Da Vinci Code','Dan Brown'),
('Angels and Demons','Dan Brown'),
('Inferno','Dan Brown'),
('The Kite Runner','Khaled Hosseini'),
('A Thousand Splendid Suns','Khaled Hosseini'),
('The Book Thief','Markus Zusak'),
('Life of Pi','Yann Martel'),
('The Fault in Our Stars','John Green'),
('Looking for Alaska','John Green'),
('Twilight','Stephenie Meyer'),
('New Moon','Stephenie Meyer'),
('Eclipse','Stephenie Meyer'),
('Breaking Dawn','Stephenie Meyer'),
('The Hunger Games','Suzanne Collins'),
('Catching Fire','Suzanne Collins'),
('Mockingjay','Suzanne Collins'),
('The Shining','Stephen King'),
('It','Stephen King'),
('Misery','Stephen King'),
('The Stand','Stephen King'),
('Dracula','Bram Stoker'),
('Frankenstein','Mary Shelley'),
('The Odyssey','Homer'),
('The Iliad','Homer'),
('Moby Dick','Herman Melville'),
('War and Peace','Leo Tolstoy'),
('Anna Karenina','Leo Tolstoy'),
('The Brothers Karamazov','Fyodor Dostoevsky'),
('Crime and Punishment','Fyodor Dostoevsky'),
('The Little Prince','Antoine de Saint-Exupéry'),
('Don Quixote','Miguel de Cervantes');